// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlAJ5kFuNKq-gsT6xeNlDEQ99p6gaCJmA',
    appId: '1:570197047695:web:6d8aefc4adcfebd7ec73fa',
    messagingSenderId: '570197047695',
    projectId: 'medihelp-2cbab',
    authDomain: 'medihelp-2cbab.firebaseapp.com',
    storageBucket: 'medihelp-2cbab.firebasestorage.app',
    measurementId: 'G-SY2HTNH0PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6iXkmBVW8NXH9tXv3XaPh2Z59M0bW-8',
    appId: '1:570197047695:android:d03c69925b1b2ec0ec73fa',
    messagingSenderId: '570197047695',
    projectId: 'medihelp-2cbab',
    storageBucket: 'medihelp-2cbab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ33MAN9L0Tv36XI6_Y3k9qUUeImt7jkA',
    appId: '1:570197047695:ios:5a467e2d8c86c60aec73fa',
    messagingSenderId: '570197047695',
    projectId: 'medihelp-2cbab',
    storageBucket: 'medihelp-2cbab.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ33MAN9L0Tv36XI6_Y3k9qUUeImt7jkA',
    appId: '1:570197047695:ios:5a467e2d8c86c60aec73fa',
    messagingSenderId: '570197047695',
    projectId: 'medihelp-2cbab',
    storageBucket: 'medihelp-2cbab.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlAJ5kFuNKq-gsT6xeNlDEQ99p6gaCJmA',
    appId: '1:570197047695:web:87851a67d25ef8b1ec73fa',
    messagingSenderId: '570197047695',
    projectId: 'medihelp-2cbab',
    authDomain: 'medihelp-2cbab.firebaseapp.com',
    storageBucket: 'medihelp-2cbab.firebasestorage.app',
    measurementId: 'G-Y9CGQ1162Z',
  );
}
